#define _CFFI_USE_EMBEDDING
#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

#define _CFFI_MODULE_NAME  "pypy-c-pydrofoil-riscv"
static const char _CFFI_PYTHON_STARTUP_CODE[] = {
// # NB. this is not a string because of a size limit in MSVC
// 'import _pydrofoil\n
105,109,112,111,114,116,32,95,112,121,100,114,111,102,111,105,108,10,
// 'from collections import Counter\n
102,114,111,109,32,99,111,108,108,101,99,116,105,111,110,115,32,105,109,112,
111,114,116,32,67,111,117,110,116,101,114,10,
// '\n
10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_disambiguation_state():\n
100,101,102,32,100,105,102,102,116,101,115,116,95,100,105,115,97,109,98,105,
103,117,97,116,105,111,110,95,115,116,97,116,101,40,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_memcpy(addr, buf, n, direction):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,109,101,109,99,112,121,40,
97,100,100,114,44,32,98,117,102,44,32,110,44,32,100,105,114,101,99,116,105,111,
110,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_regcpy(dut, direction, on_demand):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,114,101,103,99,112,121,40,
100,117,116,44,32,100,105,114,101,99,116,105,111,110,44,32,111,110,95,100,101,
109,97,110,100,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    # cpu.read_register()\n
32,32,32,32,35,32,99,112,117,46,114,101,97,100,95,114,101,103,105,115,116,101,
114,40,41,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_csrcpy(dut, direction):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,99,115,114,99,112,121,40,100,
117,116,44,32,100,105,114,101,99,116,105,111,110,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    # cpu.lowlevel.read_CSR()\n
32,32,32,32,35,32,99,112,117,46,108,111,119,108,101,118,101,108,46,114,101,97,
100,95,67,83,82,40,41,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_pmpcpy(dut, direction):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,112,109,112,99,112,121,40,
100,117,116,44,32,100,105,114,101,99,116,105,111,110,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_pmp_cfg_cpy(dut, direction):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,112,109,112,95,99,102,103,
95,99,112,121,40,100,117,116,44,32,100,105,114,101,99,116,105,111,110,41,58,
10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_uarchstatus_sync(dut):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,117,97,114,99,104,115,116,
97,116,117,115,95,115,121,110,99,40,100,117,116,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def update_dynamic_config(config):\n
100,101,102,32,117,112,100,97,116,101,95,100,121,110,97,109,105,99,95,99,111,
110,102,105,103,40,99,111,110,102,105,103,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_exec(n):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,101,120,101,99,40,110,41,58,
10,
// '    for _ in range(n):\n
32,32,32,32,102,111,114,32,95,32,105,110,32,114,97,110,103,101,40,110,41,58,
10,
// '        cpu.step()\n
32,32,32,32,32,32,32,32,99,112,117,46,115,116,101,112,40,41,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_skip_one(isRVC, wen, wdest, wdata):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,115,107,105,112,95,111,110,
101,40,105,115,82,86,67,44,32,119,101,110,44,32,119,100,101,115,116,44,32,119,
100,97,116,97,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    # Currently Pydrofoil does not support this ?\n
32,32,32,32,35,32,67,117,114,114,101,110,116,108,121,32,80,121,100,114,111,102,
111,105,108,32,100,111,101,115,32,110,111,116,32,115,117,112,112,111,114,116,
32,116,104,105,115,32,63,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_init(port):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,105,110,105,116,40,112,111,
114,116,41,58,10,
// '    # WTF IS `port` ?\n
32,32,32,32,35,32,87,84,70,32,73,83,32,96,112,111,114,116,96,32,63,10,
// '    # Spike does nothing with it!\n
32,32,32,32,35,32,83,112,105,107,101,32,100,111,101,115,32,110,111,116,104,105,
110,103,32,119,105,116,104,32,105,116,33,10,
// '    # TODO: select & load elf during build phase\n
32,32,32,32,35,32,84,79,68,79,58,32,115,101,108,101,99,116,32,38,32,108,111,
97,100,32,101,108,102,32,100,117,114,105,110,103,32,98,117,105,108,100,32,112,
104,97,115,101,10,
// '    cpu = _pydrofoil.RISCV64("./riscv/input/rv64-linux-4.15.0-gcc-7.2.0-64mb.bbl", dtb=True)\n
32,32,32,32,99,112,117,32,61,32,95,112,121,100,114,111,102,111,105,108,46,82,
73,83,67,86,54,52,40,34,46,47,114,105,115,99,118,47,105,110,112,117,116,47,114,
118,54,52,45,108,105,110,117,120,45,52,46,49,53,46,48,45,103,99,99,45,55,46,
50,46,48,45,54,52,109,98,46,98,98,108,34,44,32,100,116,98,61,84,114,117,101,
41,10,
// '    cpu.set_verbosity(0)\n
32,32,32,32,99,112,117,46,115,101,116,95,118,101,114,98,111,115,105,116,121,
40,48,41,10,
// '    \n
32,32,32,32,10,
// '    # TODO: record variable with Counter\n
32,32,32,32,35,32,84,79,68,79,58,32,114,101,99,111,114,100,32,118,97,114,105,
97,98,108,101,32,119,105,116,104,32,67,111,117,110,116,101,114,10,
// '    # so that we can later dump extra info\n
32,32,32,32,35,32,115,111,32,116,104,97,116,32,119,101,32,99,97,110,32,108,97,
116,101,114,32,100,117,109,112,32,101,120,116,114,97,32,105,110,102,111,10,
// '    # cnt = Counter()\n
32,32,32,32,35,32,99,110,116,32,61,32,67,111,117,110,116,101,114,40,41,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_raise_intr(NO):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,114,97,105,115,101,95,105,
110,116,114,40,78,79,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_dirty_fsvs(dirties):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,100,105,114,116,121,95,102,
115,118,115,40,100,105,114,116,105,101,115,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_raise_critical_error():\n
100,101,102,32,100,105,102,102,116,101,115,116,95,114,97,105,115,101,95,99,114,
105,116,105,99,97,108,95,101,114,114,111,114,40,41,58,10,
// "    # This simply change state variable on Spike's side\n
32,32,32,32,35,32,84,104,105,115,32,115,105,109,112,108,121,32,99,104,97,110,
103,101,32,115,116,97,116,101,32,118,97,114,105,97,98,108,101,32,111,110,32,
83,112,105,107,101,39,115,32,115,105,100,101,10,
// '    # Not sure if we should mimic such behaviour...\n
32,32,32,32,35,32,78,111,116,32,115,117,114,101,32,105,102,32,119,101,32,115,
104,111,117,108,100,32,109,105,109,105,99,32,115,117,99,104,32,98,101,104,97,
118,105,111,117,114,46,46,46,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def isa_reg_display():\n
100,101,102,32,105,115,97,95,114,101,103,95,100,105,115,112,108,97,121,40,41,
58,10,
// '    # TODO: pretty print\n
32,32,32,32,35,32,84,79,68,79,58,32,112,114,101,116,116,121,32,112,114,105,110,
116,10,
// '    print(cpu.register_info())\n
32,32,32,32,112,114,105,110,116,40,99,112,117,46,114,101,103,105,115,116,101,
114,95,105,110,102,111,40,41,41,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_display():\n
100,101,102,32,100,105,102,102,116,101,115,116,95,100,105,115,112,108,97,121,
40,41,58,10,
// '    # TODO: Check simpleprofiler.py\n
32,32,32,32,35,32,84,79,68,79,58,32,67,104,101,99,107,32,115,105,109,112,108,
101,112,114,111,102,105,108,101,114,46,112,121,10,
// '    # cpu.memory_info(), cpu.register_info(), etc.\n
32,32,32,32,35,32,99,112,117,46,109,101,109,111,114,121,95,105,110,102,111,40,
41,44,32,99,112,117,46,114,101,103,105,115,116,101,114,95,105,110,102,111,40,
41,44,32,101,116,99,46,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_store_commit(addr, data, mask):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,115,116,111,114,101,95,99,
111,109,109,105,116,40,97,100,100,114,44,32,100,97,116,97,44,32,109,97,115,107,
41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_guided_exec():\n
100,101,102,32,100,105,102,102,116,101,115,116,95,103,117,105,100,101,100,95,
101,120,101,99,40,41,58,10,
// '    cpu.step()\n
32,32,32,32,99,112,117,46,115,116,101,112,40,41,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def debug_mem_sync(addr, buf, n):\n
100,101,102,32,100,101,98,117,103,95,109,101,109,95,115,121,110,99,40,97,100,
100,114,44,32,98,117,102,44,32,110,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_load_flash_v2(flash_bin, size):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,108,111,97,100,95,102,108,
97,115,104,95,118,50,40,102,108,97,115,104,95,98,105,110,44,32,115,105,122,101,
41,58,10,
// '    # Seem unsupported ?\n
32,32,32,32,35,32,83,101,101,109,32,117,110,115,117,112,112,111,114,116,101,
100,32,63,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_load_flash(flash_bin_file, size):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,108,111,97,100,95,102,108,
97,115,104,40,102,108,97,115,104,95,98,105,110,95,102,105,108,101,44,32,115,
105,122,101,41,58,10,
// '    # Seem unsupported ?\n
32,32,32,32,35,32,83,101,101,109,32,117,110,115,117,112,112,111,114,116,101,
100,32,63,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_set_mhartid(mhartid):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,115,101,116,95,109,104,97,
114,116,105,100,40,109,104,97,114,116,105,100,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_close():\n
100,101,102,32,100,105,102,102,116,101,115,116,95,99,108,111,115,101,40,41,58,
10,
// '    exit(0)\n
32,32,32,32,101,120,105,116,40,48,41,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_set_ramsize(size):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,115,101,116,95,114,97,109,
115,105,122,101,40,115,105,122,101,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
// '\n
10,
// '@ffi.def_extern\n
64,102,102,105,46,100,101,102,95,101,120,116,101,114,110,10,
// 'def difftest_non_reg_interrupt_pending(non_reg_interrupt_pending):\n
100,101,102,32,100,105,102,102,116,101,115,116,95,110,111,110,95,114,101,103,
95,105,110,116,101,114,114,117,112,116,95,112,101,110,100,105,110,103,40,110,
111,110,95,114,101,103,95,105,110,116,101,114,114,117,112,116,95,112,101,110,
100,105,110,103,41,58,10,
// '    # TODO: implement this\n
32,32,32,32,35,32,84,79,68,79,58,32,105,109,112,108,101,109,101,110,116,32,116,
104,105,115,10,
// '    pass\n
32,32,32,32,112,97,115,115,10,
0 };
#ifdef PYPY_VERSION
# define _CFFI_PYTHON_STARTUP_FUNC  _cffi_pypyinit_pypy-c-pydrofoil-riscv
#elif PY_MAJOR_VERSION >= 3
# define _CFFI_PYTHON_STARTUP_FUNC  PyInit_pypy-c-pydrofoil-riscv
#else
# define _CFFI_PYTHON_STARTUP_FUNC  initpypy-c-pydrofoil-riscv
#endif

/***** Support code for embedding *****/

#ifdef __cplusplus
extern "C" {
#endif


#if defined(_WIN32)
#  define CFFI_DLLEXPORT  __declspec(dllexport)
#elif defined(__GNUC__)
#  define CFFI_DLLEXPORT  __attribute__((visibility("default")))
#else
#  define CFFI_DLLEXPORT  /* nothing */
#endif


/* There are two global variables of type _cffi_call_python_fnptr:

   * _cffi_call_python, which we declare just below, is the one called
     by ``extern "Python"`` implementations.

   * _cffi_call_python_org, which on CPython is actually part of the
     _cffi_exports[] array, is the function pointer copied from
     _cffi_backend.  If _cffi_start_python() fails, then this is set
     to NULL; otherwise, it should never be NULL.

   After initialization is complete, both are equal.  However, the
   first one remains equal to &_cffi_start_and_call_python until the
   very end of initialization, when we are (or should be) sure that
   concurrent threads also see a completely initialized world, and
   only then is it changed.
*/
#undef _cffi_call_python
typedef void (*_cffi_call_python_fnptr)(struct _cffi_externpy_s *, char *);
static void _cffi_start_and_call_python(struct _cffi_externpy_s *, char *);
static _cffi_call_python_fnptr _cffi_call_python = &_cffi_start_and_call_python;


#ifndef _MSC_VER
   /* --- Assuming a GCC not infinitely old --- */
# define cffi_compare_and_swap(l,o,n)  __sync_bool_compare_and_swap(l,o,n)
# define cffi_write_barrier()          __sync_synchronize()
# if !defined(__amd64__) && !defined(__x86_64__) &&   \
     !defined(__i386__) && !defined(__i386)
#   define cffi_read_barrier()         __sync_synchronize()
# else
#   define cffi_read_barrier()         (void)0
# endif
#else
   /* --- Windows threads version --- */
# include <Windows.h>
# define cffi_compare_and_swap(l,o,n) \
                               (InterlockedCompareExchangePointer(l,n,o) == (o))
# define cffi_write_barrier()       InterlockedCompareExchange(&_cffi_dummy,0,0)
# define cffi_read_barrier()           (void)0
static volatile LONG _cffi_dummy;
#endif

#ifdef WITH_THREAD
# ifndef _MSC_VER
#  include <pthread.h>
   static pthread_mutex_t _cffi_embed_startup_lock;
# else
   static CRITICAL_SECTION _cffi_embed_startup_lock;
# endif
  static char _cffi_embed_startup_lock_ready = 0;
#endif

static void _cffi_acquire_reentrant_mutex(void)
{
    static void *volatile lock = NULL;

    while (!cffi_compare_and_swap(&lock, NULL, (void *)1)) {
        /* should ideally do a spin loop instruction here, but
           hard to do it portably and doesn't really matter I
           think: pthread_mutex_init() should be very fast, and
           this is only run at start-up anyway. */
    }

#ifdef WITH_THREAD
    if (!_cffi_embed_startup_lock_ready) {
# ifndef _MSC_VER
        pthread_mutexattr_t attr;
        pthread_mutexattr_init(&attr);
        pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
        pthread_mutex_init(&_cffi_embed_startup_lock, &attr);
# else
        InitializeCriticalSection(&_cffi_embed_startup_lock);
# endif
        _cffi_embed_startup_lock_ready = 1;
    }
#endif

    while (!cffi_compare_and_swap(&lock, (void *)1, NULL))
        ;

#ifndef _MSC_VER
    pthread_mutex_lock(&_cffi_embed_startup_lock);
#else
    EnterCriticalSection(&_cffi_embed_startup_lock);
#endif
}

static void _cffi_release_reentrant_mutex(void)
{
#ifndef _MSC_VER
    pthread_mutex_unlock(&_cffi_embed_startup_lock);
#else
    LeaveCriticalSection(&_cffi_embed_startup_lock);
#endif
}


/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION

#ifndef CFFI_MESSAGEBOX
# ifdef _MSC_VER
#  define CFFI_MESSAGEBOX  1
# else
#  define CFFI_MESSAGEBOX  0
# endif
#endif


#if CFFI_MESSAGEBOX
/* Windows only: logic to take the Python-CFFI embedding logic
   initialization errors and display them in a background thread
   with MessageBox.  The idea is that if the whole program closes
   as a result of this problem, then likely it is already a console
   program and you can read the stderr output in the console too.
   If it is not a console program, then it will likely show its own
   dialog to complain, or generally not abruptly close, and for this
   case the background thread should stay alive.
*/
static void *volatile _cffi_bootstrap_text;

static PyObject *_cffi_start_error_capture(void)
{
    PyObject *result = NULL;
    PyObject *x, *m, *bi;

    if (InterlockedCompareExchangePointer(&_cffi_bootstrap_text,
            (void *)1, NULL) != NULL)
        return (PyObject *)1;

    m = PyImport_AddModule("_cffi_error_capture");
    if (m == NULL)
        goto error;

    result = PyModule_GetDict(m);
    if (result == NULL)
        goto error;

#if PY_MAJOR_VERSION >= 3
    bi = PyImport_ImportModule("builtins");
#else
    bi = PyImport_ImportModule("__builtin__");
#endif
    if (bi == NULL)
        goto error;
    PyDict_SetItemString(result, "__builtins__", bi);
    Py_DECREF(bi);

    x = PyRun_String(
        "import sys\n"
        "class FileLike:\n"
        "  def write(self, x):\n"
        "    try:\n"
        "      of.write(x)\n"
        "    except: pass\n"
        "    self.buf += x\n"
        "  def flush(self):\n"
        "    pass\n"
        "fl = FileLike()\n"
        "fl.buf = ''\n"
        "of = sys.stderr\n"
        "sys.stderr = fl\n"
        "def done():\n"
        "  sys.stderr = of\n"
        "  return fl.buf\n",   /* make sure the returned value stays alive */
        Py_file_input,
        result, result);
    Py_XDECREF(x);

 error:
    if (PyErr_Occurred())
    {
        PyErr_WriteUnraisable(Py_None);
        PyErr_Clear();
    }
    return result;
}

#pragma comment(lib, "user32.lib")

static DWORD WINAPI _cffi_bootstrap_dialog(LPVOID ignored)
{
    Sleep(666);    /* may be interrupted if the whole process is closing */
#if PY_MAJOR_VERSION >= 3
    MessageBoxW(NULL, (wchar_t *)_cffi_bootstrap_text,
                L"Python-CFFI error",
                MB_OK | MB_ICONERROR);
#else
    MessageBoxA(NULL, (char *)_cffi_bootstrap_text,
                "Python-CFFI error",
                MB_OK | MB_ICONERROR);
#endif
    _cffi_bootstrap_text = NULL;
    return 0;
}

static void _cffi_stop_error_capture(PyObject *ecap)
{
    PyObject *s;
    void *text;

    if (ecap == (PyObject *)1)
        return;

    if (ecap == NULL)
        goto error;

    s = PyRun_String("done()", Py_eval_input, ecap, ecap);
    if (s == NULL)
        goto error;

    /* Show a dialog box, but in a background thread, and
       never show multiple dialog boxes at once. */
#if PY_MAJOR_VERSION >= 3
    text = PyUnicode_AsWideCharString(s, NULL);
#else
    text = PyString_AsString(s);
#endif

    _cffi_bootstrap_text = text;

    if (text != NULL)
    {
        HANDLE h;
        h = CreateThread(NULL, 0, _cffi_bootstrap_dialog,
                         NULL, 0, NULL);
        if (h != NULL)
            CloseHandle(h);
    }
    /* decref the string, but it should stay alive as 'fl.buf'
       in the small module above.  It will really be freed only if
       we later get another similar error.  So it's a leak of at
       most one copy of the small module.  That's fine for this
       situation which is usually a "fatal error" anyway. */
    Py_DECREF(s);
    PyErr_Clear();
    return;

  error:
    _cffi_bootstrap_text = NULL;
    PyErr_Clear();
}

#else

static PyObject *_cffi_start_error_capture(void) { return NULL; }
static void _cffi_stop_error_capture(PyObject *ecap) { }

#endif


#define _cffi_call_python_org  _cffi_exports[_CFFI_CPIDX]

PyMODINIT_FUNC _CFFI_PYTHON_STARTUP_FUNC(void);   /* forward */

static void _cffi_py_initialize(void)
{
    /* XXX use initsigs=0, which "skips initialization registration of
       signal handlers, which might be useful when Python is
       embedded" according to the Python docs.  But review and think
       if it should be a user-controllable setting.

       XXX we should also give a way to write errors to a buffer
       instead of to stderr.

       XXX if importing 'site' fails, CPython (any version) calls
       exit().  Should we try to work around this behavior here?
    */
    Py_InitializeEx(0);
}

static int _cffi_initialize_python(void)
{
    /* This initializes Python, imports _cffi_backend, and then the
       present .dll/.so is set up as a CPython C extension module.
    */
    int result;
    PyGILState_STATE state;
    PyObject *pycode=NULL, *global_dict=NULL, *x;
    PyObject *builtins;

    state = PyGILState_Ensure();

    /* Call the initxxx() function from the present module.  It will
       create and initialize us as a CPython extension module, instead
       of letting the startup Python code do it---it might reimport
       the same .dll/.so and get maybe confused on some platforms.
       It might also have troubles locating the .dll/.so again for all
       I know.
    */
    (void)_CFFI_PYTHON_STARTUP_FUNC();
    if (PyErr_Occurred())
        goto error;

    /* Now run the Python code provided to ffi.embedding_init_code().
     */
    pycode = Py_CompileString(_CFFI_PYTHON_STARTUP_CODE,
                              "<init code for '" _CFFI_MODULE_NAME "'>",
                              Py_file_input);
    if (pycode == NULL)
        goto error;
    global_dict = PyDict_New();
    if (global_dict == NULL)
        goto error;
    builtins = PyEval_GetBuiltins();
    if (builtins == NULL)
        goto error;
    if (PyDict_SetItemString(global_dict, "__builtins__", builtins) < 0)
        goto error;
    x = PyEval_EvalCode(
#if PY_MAJOR_VERSION < 3
                        (PyCodeObject *)
#endif
                        pycode, global_dict, global_dict);
    if (x == NULL)
        goto error;
    Py_DECREF(x);

    /* Done!  Now if we've been called from
       _cffi_start_and_call_python() in an ``extern "Python"``, we can
       only hope that the Python code did correctly set up the
       corresponding @ffi.def_extern() function.  Otherwise, the
       general logic of ``extern "Python"`` functions (inside the
       _cffi_backend module) will find that the reference is still
       missing and print an error.
     */
    result = 0;
 done:
    Py_XDECREF(pycode);
    Py_XDECREF(global_dict);
    PyGILState_Release(state);
    return result;

 error:;
    {
        /* Print as much information as potentially useful.
           Debugging load-time failures with embedding is not fun
        */
        PyObject *ecap;
        PyObject *exception, *v, *tb, *f, *modules, *mod;
        PyErr_Fetch(&exception, &v, &tb);
        ecap = _cffi_start_error_capture();
        f = PySys_GetObject((char *)"stderr");
        if (f != NULL && f != Py_None) {
            PyFile_WriteString(
                "Failed to initialize the Python-CFFI embedding logic:\n\n", f);
        }

        if (exception != NULL) {
            PyErr_NormalizeException(&exception, &v, &tb);
            PyErr_Display(exception, v, tb);
        }
        Py_XDECREF(exception);
        Py_XDECREF(v);
        Py_XDECREF(tb);

        if (f != NULL && f != Py_None) {
            PyFile_WriteString("\nFrom: " _CFFI_MODULE_NAME
                               "\ncompiled with cffi version: 1.18.0.dev0"
                               "\n_cffi_backend module: ", f);
            modules = PyImport_GetModuleDict();
            mod = PyDict_GetItemString(modules, "_cffi_backend");
            if (mod == NULL) {
                PyFile_WriteString("not loaded", f);
            }
            else {
                v = PyObject_GetAttrString(mod, "__file__");
                PyFile_WriteObject(v, f, 0);
                Py_XDECREF(v);
            }
            PyFile_WriteString("\nsys.path: ", f);
            PyFile_WriteObject(PySys_GetObject((char *)"path"), f, 0);
            PyFile_WriteString("\n\n", f);
        }
        _cffi_stop_error_capture(ecap);
    }
    result = -1;
    goto done;
}

#if PY_VERSION_HEX < 0x03080000
PyAPI_DATA(char *) _PyParser_TokenNames[];  /* from CPython */
#endif

static int _cffi_carefully_make_gil(void)
{
    /* This does the basic initialization of Python.  It can be called
       completely concurrently from unrelated threads.  It assumes
       that we don't hold the GIL before (if it exists), and we don't
       hold it afterwards.

       (What it really does used to be completely different in Python 2
       and Python 3, with the Python 2 solution avoiding the spin-lock
       around the Py_InitializeEx() call.  However, after recent changes
       to CPython 2.7 (issue #358) it no longer works.  So we use the
       Python 3 solution everywhere.)

       This initializes Python by calling Py_InitializeEx().
       Important: this must not be called concurrently at all.
       So we use a global variable as a simple spin lock.  This global
       variable must be from 'libpythonX.Y.so', not from this
       cffi-based extension module, because it must be shared from
       different cffi-based extension modules.

       In Python < 3.8, we choose
       _PyParser_TokenNames[0] as a completely arbitrary pointer value
       that is never written to.  The default is to point to the
       string "ENDMARKER".  We change it temporarily to point to the
       next character in that string.  (Yes, I know it's REALLY
       obscure.)

       In Python >= 3.8, this string array is no longer writable, so
       instead we pick PyCapsuleType.tp_version_tag.  We can't change
       Python < 3.8 because someone might use a mixture of cffi
       embedded modules, some of which were compiled before this file
       changed.

       In Python >= 3.12, this stopped working because that particular
       tp_version_tag gets modified during interpreter startup.  It's
       arguably a bad idea before 3.12 too, but again we can't change
       that because someone might use a mixture of cffi embedded
       modules, and no-one reported a bug so far.  In Python >= 3.12
       we go instead for PyCapsuleType.tp_as_buffer, which is supposed
       to always be NULL.  We write to it temporarily a pointer to
       a struct full of NULLs, which is semantically the same.
    */

#ifdef WITH_THREAD
# if PY_VERSION_HEX < 0x03080000
    char *volatile *lock = (char *volatile *)_PyParser_TokenNames;
    char *old_value, *locked_value;

    while (1) {    /* spin loop */
        old_value = *lock;
        locked_value = old_value + 1;
        if (old_value[0] == 'E') {
            assert(old_value[1] == 'N');
            if (cffi_compare_and_swap(lock, old_value, locked_value))
                break;
        }
        else {
            assert(old_value[0] == 'N');
            /* should ideally do a spin loop instruction here, but
               hard to do it portably and doesn't really matter I
               think: PyEval_InitThreads() should be very fast, and
               this is only run at start-up anyway. */
        }
    }
# else
#  if PY_VERSION_HEX < 0x030C0000
    int volatile *lock = (int volatile *)&PyCapsule_Type.tp_version_tag;
    int old_value, locked_value = -42;
    assert(!(PyCapsule_Type.tp_flags & Py_TPFLAGS_HAVE_VERSION_TAG));
#  else
    static struct ebp_s { PyBufferProcs buf; int mark; } empty_buffer_procs;
    empty_buffer_procs.mark = -42;
    PyBufferProcs *volatile *lock = (PyBufferProcs *volatile *)
        &PyCapsule_Type.tp_as_buffer;
    PyBufferProcs *old_value, *locked_value = &empty_buffer_procs.buf;
#  endif

    while (1) {    /* spin loop */
        old_value = *lock;
        if (old_value == 0) {
            if (cffi_compare_and_swap(lock, old_value, locked_value))
                break;
        }
        else {
#  if PY_VERSION_HEX < 0x030C0000
            assert(old_value == locked_value);
#  else
            /* The pointer should point to a possibly different
               empty_buffer_procs from another C extension module */
            assert(((struct ebp_s *)old_value)->mark == -42);
#  endif
            /* should ideally do a spin loop instruction here, but
               hard to do it portably and doesn't really matter I
               think: PyEval_InitThreads() should be very fast, and
               this is only run at start-up anyway. */
        }
    }
# endif
#endif

    /* call Py_InitializeEx() */
    if (!Py_IsInitialized()) {
        _cffi_py_initialize();
#if PY_VERSION_HEX < 0x03070000
        PyEval_InitThreads();
#endif
        PyEval_SaveThread();  /* release the GIL */
        /* the returned tstate must be the one that has been stored into the
           autoTLSkey by _PyGILState_Init() called from Py_Initialize(). */
    }
    else {
#if PY_VERSION_HEX < 0x03070000
        /* PyEval_InitThreads() is always a no-op from CPython 3.7 */
        PyGILState_STATE state = PyGILState_Ensure();
        PyEval_InitThreads();
        PyGILState_Release(state);
#endif
    }

#ifdef WITH_THREAD
    /* release the lock */
    while (!cffi_compare_and_swap(lock, locked_value, old_value))
        ;
#endif

    return 0;
}

/**********  end CPython-specific section  **********/


#else


/**********  PyPy-specific section  **********/

PyMODINIT_FUNC _CFFI_PYTHON_STARTUP_FUNC(const void *[]);   /* forward */

static struct _cffi_pypy_init_s {
    const char *name;
    void *func;    /* function pointer */
    const char *code;
} _cffi_pypy_init = {
    _CFFI_MODULE_NAME,
    _CFFI_PYTHON_STARTUP_FUNC,
    _CFFI_PYTHON_STARTUP_CODE,
};

extern int pypy_carefully_make_gil(const char *);
extern int pypy_init_embedded_cffi_module(int, struct _cffi_pypy_init_s *);

static int _cffi_carefully_make_gil(void)
{
    return pypy_carefully_make_gil(_CFFI_MODULE_NAME);
}

static int _cffi_initialize_python(void)
{
    return pypy_init_embedded_cffi_module(0xB011, &_cffi_pypy_init);
}

/**********  end PyPy-specific section  **********/


#endif


#ifdef __GNUC__
__attribute__((noinline))
#endif
static _cffi_call_python_fnptr _cffi_start_python(void)
{
    /* Delicate logic to initialize Python.  This function can be
       called multiple times concurrently, e.g. when the process calls
       its first ``extern "Python"`` functions in multiple threads at
       once.  It can also be called recursively, in which case we must
       ignore it.  We also have to consider what occurs if several
       different cffi-based extensions reach this code in parallel
       threads---it is a different copy of the code, then, and we
       can't have any shared global variable unless it comes from
       'libpythonX.Y.so'.

       Idea:

       * _cffi_carefully_make_gil(): "carefully" call
         PyEval_InitThreads() (possibly with Py_InitializeEx() first).

       * then we use a (local) custom lock to make sure that a call to this
         cffi-based extension will wait if another call to the *same*
         extension is running the initialization in another thread.
         It is reentrant, so that a recursive call will not block, but
         only one from a different thread.

       * then we grab the GIL and (Python 2) we call Py_InitializeEx().
         At this point, concurrent calls to Py_InitializeEx() are not
         possible: we have the GIL.

       * do the rest of the specific initialization, which may
         temporarily release the GIL but not the custom lock.
         Only release the custom lock when we are done.
    */
    static char called = 0;

    if (_cffi_carefully_make_gil() != 0)
        return NULL;

    _cffi_acquire_reentrant_mutex();

    /* Here the GIL exists, but we don't have it.  We're only protected
       from concurrency by the reentrant mutex. */

    /* This file only initializes the embedded module once, the first
       time this is called, even if there are subinterpreters. */
    if (!called) {
        called = 1;  /* invoke _cffi_initialize_python() only once,
                        but don't set '_cffi_call_python' right now,
                        otherwise concurrent threads won't call
                        this function at all (we need them to wait) */
        if (_cffi_initialize_python() == 0) {
            /* now initialization is finished.  Switch to the fast-path. */

            /* We would like nobody to see the new value of
               '_cffi_call_python' without also seeing the rest of the
               data initialized.  However, this is not possible.  But
               the new value of '_cffi_call_python' is the function
               'cffi_call_python()' from _cffi_backend.  So:  */
            cffi_write_barrier();
            /* ^^^ we put a write barrier here, and a corresponding
               read barrier at the start of cffi_call_python().  This
               ensures that after that read barrier, we see everything
               done here before the write barrier.
            */

            assert(_cffi_call_python_org != NULL);
            _cffi_call_python = (_cffi_call_python_fnptr)_cffi_call_python_org;
        }
        else {
            /* initialization failed.  Reset this to NULL, even if it was
               already set to some other value.  Future calls to
               _cffi_start_python() are still forced to occur, and will
               always return NULL from now on. */
            _cffi_call_python_org = NULL;
        }
    }

    _cffi_release_reentrant_mutex();

    return (_cffi_call_python_fnptr)_cffi_call_python_org;
}

static
void _cffi_start_and_call_python(struct _cffi_externpy_s *externpy, char *args)
{
    _cffi_call_python_fnptr fnptr;
    int current_err = errno;
#ifdef _MSC_VER
    int current_lasterr = GetLastError();
#endif
    fnptr = _cffi_start_python();
    if (fnptr == NULL) {
        fprintf(stderr, "function %s() called, but initialization code "
                        "failed.  Returning 0.\n", externpy->name);
        memset(args, 0, externpy->size_of_result);
    }
#ifdef _MSC_VER
    SetLastError(current_lasterr);
#endif
    errno = current_err;

    if (fnptr != NULL)
        fnptr(externpy, args);
}


/* The cffi_start_python() function makes sure Python is initialized
   and our cffi module is set up.  It can be called manually from the
   user C code.  The same effect is obtained automatically from any
   dll-exported ``extern "Python"`` function.  This function returns
   -1 if initialization failed, 0 if all is OK.  */
_CFFI_UNUSED_FN
static int cffi_start_python(void)
{
    if (_cffi_call_python == &_cffi_start_and_call_python) {
        if (_cffi_start_python() == NULL)
            return -1;
    }
    cffi_read_barrier();
    return 0;
}

#undef cffi_compare_and_swap
#undef cffi_write_barrier
#undef cffi_read_barrier

#ifdef __cplusplus
}
#endif

/************************************************************/



/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // _Bool()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 37), // int()(uint64_t *, uint64_t *, uint8_t *)
/*  3 */ _CFFI_OP(_CFFI_OP_POINTER, 16), // uint64_t *
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 84), // uint8_t *
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION, 37), // int()(void)
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 16), // uint64_t()(void *)
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 104), // void *
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(_Bool, _Bool, uint32_t, uint64_t)
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 14 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 15 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22), // uint32_t
/* 16 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(char const *, size_t)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 67), // char const *
/* 20 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28), // size_t
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 22 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(diff_context_t *, _Bool, _Bool)
/* 23 */ _CFFI_OP(_CFFI_OP_POINTER, 68), // diff_context_t *
/* 24 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 25 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(diff_non_reg_int *)
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 69), // diff_non_reg_int *
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 30 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(diff_ref_config *)
/* 31 */ _CFFI_OP(_CFFI_OP_POINTER, 70), // diff_ref_config *
/* 32 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(diff_uarch_status *)
/* 34 */ _CFFI_OP(_CFFI_OP_POINTER, 71), // diff_uarch_status *
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 36 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(int)
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 38 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(size_t)
/* 40 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 41 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 42 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(uint64_t)
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 44 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 45 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(uint64_t, void *, size_t)
/* 46 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 47 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 48 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 49 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 50 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(uint64_t, void *, size_t, _Bool)
/* 51 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24),
/* 52 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 53 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 55 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 56 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(uint8_t const *, size_t)
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 84), // uint8_t const *
/* 58 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 59 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 60 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(void *, _Bool)
/* 61 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 63 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 64 */ _CFFI_OP(_CFFI_OP_FUNCTION, 104), // void()(void)
/* 65 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 66 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // _Bool(*)(void)
/* 67 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 68 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // diff_context_t
/* 69 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // diff_non_reg_int
/* 70 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // diff_ref_config
/* 71 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // diff_uarch_status
/* 72 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // int(*)(uint64_t *, uint64_t *, uint8_t *)
/* 73 */ _CFFI_OP(_CFFI_OP_POINTER, 7), // int(*)(void)
/* 74 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 20), // uint16_t
/* 75 */ _CFFI_OP(_CFFI_OP_ARRAY, 74), // uint16_t[8]
/* 76 */ (_cffi_opcode_t)(8),
/* 77 */ _CFFI_OP(_CFFI_OP_ARRAY, 15), // uint32_t[4]
/* 78 */ (_cffi_opcode_t)(4),
/* 79 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // uint64_t(*)(void *)
/* 80 */ _CFFI_OP(_CFFI_OP_ARRAY, 16), // uint64_t[2]
/* 81 */ (_cffi_opcode_t)(2),
/* 82 */ _CFFI_OP(_CFFI_OP_ARRAY, 16), // uint64_t[32]
/* 83 */ (_cffi_opcode_t)(32),
/* 84 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 85 */ _CFFI_OP(_CFFI_OP_ARRAY, 84), // uint8_t[16]
/* 86 */ (_cffi_opcode_t)(16),
/* 87 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // union $1
/* 88 */ _CFFI_OP(_CFFI_OP_ARRAY, 87), // union $1[32]
/* 89 */ (_cffi_opcode_t)(32),
/* 90 */ _CFFI_OP(_CFFI_OP_POINTER, 12), // void(*)(_Bool, _Bool, uint32_t, uint64_t)
/* 91 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // void(*)(char const *, size_t)
/* 92 */ _CFFI_OP(_CFFI_OP_POINTER, 22), // void(*)(diff_context_t *, _Bool, _Bool)
/* 93 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // void(*)(diff_non_reg_int *)
/* 94 */ _CFFI_OP(_CFFI_OP_POINTER, 30), // void(*)(diff_ref_config *)
/* 95 */ _CFFI_OP(_CFFI_OP_POINTER, 33), // void(*)(diff_uarch_status *)
/* 96 */ _CFFI_OP(_CFFI_OP_POINTER, 36), // void(*)(int)
/* 97 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // void(*)(size_t)
/* 98 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // void(*)(uint64_t)
/* 99 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // void(*)(uint64_t, void *, size_t)
/* 100 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // void(*)(uint64_t, void *, size_t, _Bool)
/* 101 */ _CFFI_OP(_CFFI_OP_POINTER, 56), // void(*)(uint8_t const *, size_t)
/* 102 */ _CFFI_OP(_CFFI_OP_POINTER, 60), // void(*)(void *, _Bool)
/* 103 */ _CFFI_OP(_CFFI_OP_POINTER, 64), // void(*)(void)
/* 104 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_diff_context_t(diff_context_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { uint64_t(*tmp)[32] = &p->gpr; (void)tmp; }
  { uint64_t(*tmp)[32] = &p->fpr; (void)tmp; }
  (void)((p->priv) | 0);  /* check that 'diff_context_t.priv' is an integer */
  (void)((p->mstatus) | 0);  /* check that 'diff_context_t.mstatus' is an integer */
  (void)((p->sstatus) | 0);  /* check that 'diff_context_t.sstatus' is an integer */
  (void)((p->mepc) | 0);  /* check that 'diff_context_t.mepc' is an integer */
  (void)((p->sepc) | 0);  /* check that 'diff_context_t.sepc' is an integer */
  (void)((p->mtval) | 0);  /* check that 'diff_context_t.mtval' is an integer */
  (void)((p->stval) | 0);  /* check that 'diff_context_t.stval' is an integer */
  (void)((p->mtvec) | 0);  /* check that 'diff_context_t.mtvec' is an integer */
  (void)((p->stvec) | 0);  /* check that 'diff_context_t.stvec' is an integer */
  (void)((p->mcause) | 0);  /* check that 'diff_context_t.mcause' is an integer */
  (void)((p->scause) | 0);  /* check that 'diff_context_t.scause' is an integer */
  (void)((p->satp) | 0);  /* check that 'diff_context_t.satp' is an integer */
  (void)((p->mip) | 0);  /* check that 'diff_context_t.mip' is an integer */
  (void)((p->mie) | 0);  /* check that 'diff_context_t.mie' is an integer */
  (void)((p->mscratch) | 0);  /* check that 'diff_context_t.mscratch' is an integer */
  (void)((p->sscratch) | 0);  /* check that 'diff_context_t.sscratch' is an integer */
  (void)((p->mideleg) | 0);  /* check that 'diff_context_t.mideleg' is an integer */
  (void)((p->medeleg) | 0);  /* check that 'diff_context_t.medeleg' is an integer */
  (void)((p->pc) | 0);  /* check that 'diff_context_t.pc' is an integer */
  (void)((p->v) | 0);  /* check that 'diff_context_t.v' is an integer */
  (void)((p->mtval2) | 0);  /* check that 'diff_context_t.mtval2' is an integer */
  (void)((p->mtinst) | 0);  /* check that 'diff_context_t.mtinst' is an integer */
  (void)((p->hstatus) | 0);  /* check that 'diff_context_t.hstatus' is an integer */
  (void)((p->hideleg) | 0);  /* check that 'diff_context_t.hideleg' is an integer */
  (void)((p->hedeleg) | 0);  /* check that 'diff_context_t.hedeleg' is an integer */
  (void)((p->hcounteren) | 0);  /* check that 'diff_context_t.hcounteren' is an integer */
  (void)((p->htval) | 0);  /* check that 'diff_context_t.htval' is an integer */
  (void)((p->htinst) | 0);  /* check that 'diff_context_t.htinst' is an integer */
  (void)((p->hgatp) | 0);  /* check that 'diff_context_t.hgatp' is an integer */
  (void)((p->vsstatus) | 0);  /* check that 'diff_context_t.vsstatus' is an integer */
  (void)((p->vstvec) | 0);  /* check that 'diff_context_t.vstvec' is an integer */
  (void)((p->vsepc) | 0);  /* check that 'diff_context_t.vsepc' is an integer */
  (void)((p->vscause) | 0);  /* check that 'diff_context_t.vscause' is an integer */
  (void)((p->vstval) | 0);  /* check that 'diff_context_t.vstval' is an integer */
  (void)((p->vsatp) | 0);  /* check that 'diff_context_t.vsatp' is an integer */
  (void)((p->vsscratch) | 0);  /* check that 'diff_context_t.vsscratch' is an integer */
  /* cannot generate 'union $1[32]' in field 'vr': unknown type name */
  (void)((p->vstart) | 0);  /* check that 'diff_context_t.vstart' is an integer */
  (void)((p->vxsat) | 0);  /* check that 'diff_context_t.vxsat' is an integer */
  (void)((p->vxrm) | 0);  /* check that 'diff_context_t.vxrm' is an integer */
  (void)((p->vcsr) | 0);  /* check that 'diff_context_t.vcsr' is an integer */
  (void)((p->vl) | 0);  /* check that 'diff_context_t.vl' is an integer */
  (void)((p->vtype) | 0);  /* check that 'diff_context_t.vtype' is an integer */
  (void)((p->vlenb) | 0);  /* check that 'diff_context_t.vlenb' is an integer */
  (void)((p->fcsr) | 0);  /* check that 'diff_context_t.fcsr' is an integer */
  (void)((p->tselect) | 0);  /* check that 'diff_context_t.tselect' is an integer */
  (void)((p->tdata1) | 0);  /* check that 'diff_context_t.tdata1' is an integer */
  (void)((p->tinfo) | 0);  /* check that 'diff_context_t.tinfo' is an integer */
  (void)((p->debugMode) | 0);  /* check that 'diff_context_t.debugMode' is an integer */
  (void)((p->dcsr) | 0);  /* check that 'diff_context_t.dcsr' is an integer */
  (void)((p->dpc) | 0);  /* check that 'diff_context_t.dpc' is an integer */
  (void)((p->dscratch0) | 0);  /* check that 'diff_context_t.dscratch0' is an integer */
  (void)((p->dscratch1) | 0);  /* check that 'diff_context_t.dscratch1' is an integer */
}
struct _cffi_align_typedef_diff_context_t { char x; diff_context_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_diff_non_reg_int(diff_non_reg_int *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->platform_irp_meip) | 0);  /* check that 'diff_non_reg_int.platform_irp_meip' is an integer */
  (void)((p->platform_irp_mtip) | 0);  /* check that 'diff_non_reg_int.platform_irp_mtip' is an integer */
  (void)((p->platform_irp_msip) | 0);  /* check that 'diff_non_reg_int.platform_irp_msip' is an integer */
  (void)((p->platform_irp_seip) | 0);  /* check that 'diff_non_reg_int.platform_irp_seip' is an integer */
  (void)((p->platform_irp_stip) | 0);  /* check that 'diff_non_reg_int.platform_irp_stip' is an integer */
  (void)((p->platform_irp_vseip) | 0);  /* check that 'diff_non_reg_int.platform_irp_vseip' is an integer */
  (void)((p->platform_irp_vstip) | 0);  /* check that 'diff_non_reg_int.platform_irp_vstip' is an integer */
  (void)((p->lcofi_req) | 0);  /* check that 'diff_non_reg_int.lcofi_req' is an integer */
}
struct _cffi_align_typedef_diff_non_reg_int { char x; diff_non_reg_int y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_diff_ref_config(diff_ref_config *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->ignore_illegal_mem_access) | 0);  /* check that 'diff_ref_config.ignore_illegal_mem_access' is an integer */
  (void)((p->debug_difftest) | 0);  /* check that 'diff_ref_config.debug_difftest' is an integer */
}
struct _cffi_align_typedef_diff_ref_config { char x; diff_ref_config y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_diff_uarch_status(diff_uarch_status *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->sc_failed) | 0);  /* check that 'diff_uarch_status.sc_failed' is an integer */
}
struct _cffi_align_typedef_diff_uarch_status { char x; diff_uarch_status y; };

static struct _cffi_externpy_s _cffi_externpy__debug_mem_sync =
  { "pypy-c-pydrofoil-riscv.debug_mem_sync", 0, 0, 0 };

CFFI_DLLEXPORT void debug_mem_sync(uint64_t a0, void * a1, size_t a2)
{
  char a[24];
  char *p = a;
  *(uint64_t *)(p + 0) = a0;
  *(void * *)(p + 8) = a1;
  *(size_t *)(p + 16) = a2;
  _cffi_call_python(&_cffi_externpy__debug_mem_sync, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_close =
  { "pypy-c-pydrofoil-riscv.difftest_close", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_close(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy__difftest_close, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_csrcpy =
  { "pypy-c-pydrofoil-riscv.difftest_csrcpy", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_csrcpy(void * a0, _Bool a1)
{
  char a[16];
  char *p = a;
  *(void * *)(p + 0) = a0;
  *(_Bool *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__difftest_csrcpy, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_dirty_fsvs =
  { "pypy-c-pydrofoil-riscv.difftest_dirty_fsvs", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_dirty_fsvs(uint64_t a0)
{
  char a[8];
  char *p = a;
  *(uint64_t *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_dirty_fsvs, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_disambiguation_state =
  { "pypy-c-pydrofoil-riscv.difftest_disambiguation_state", (int)sizeof(int), 0, 0 };

CFFI_DLLEXPORT int difftest_disambiguation_state(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy__difftest_disambiguation_state, p);
  return *(int *)p;
}

static struct _cffi_externpy_s _cffi_externpy__difftest_display =
  { "pypy-c-pydrofoil-riscv.difftest_display", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_display(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy__difftest_display, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_exec =
  { "pypy-c-pydrofoil-riscv.difftest_exec", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_exec(uint64_t a0)
{
  char a[8];
  char *p = a;
  *(uint64_t *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_exec, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_guided_exec =
  { "pypy-c-pydrofoil-riscv.difftest_guided_exec", (int)sizeof(uint64_t), 0, 0 };

CFFI_DLLEXPORT uint64_t difftest_guided_exec(void * a0)
{
  char a[8];
  char *p = a;
  *(void * *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_guided_exec, p);
  return *(uint64_t *)p;
}

static struct _cffi_externpy_s _cffi_externpy__difftest_init =
  { "pypy-c-pydrofoil-riscv.difftest_init", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_init(int a0)
{
  char a[8];
  char *p = a;
  *(int *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_init, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_load_flash =
  { "pypy-c-pydrofoil-riscv.difftest_load_flash", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_load_flash(char const * a0, size_t a1)
{
  char a[16];
  char *p = a;
  *(char const * *)(p + 0) = a0;
  *(size_t *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__difftest_load_flash, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_load_flash_v2 =
  { "pypy-c-pydrofoil-riscv.difftest_load_flash_v2", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_load_flash_v2(uint8_t const * a0, size_t a1)
{
  char a[16];
  char *p = a;
  *(uint8_t const * *)(p + 0) = a0;
  *(size_t *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__difftest_load_flash_v2, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_memcpy =
  { "pypy-c-pydrofoil-riscv.difftest_memcpy", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_memcpy(uint64_t a0, void * a1, size_t a2, _Bool a3)
{
  char a[32];
  char *p = a;
  *(uint64_t *)(p + 0) = a0;
  *(void * *)(p + 8) = a1;
  *(size_t *)(p + 16) = a2;
  *(_Bool *)(p + 24) = a3;
  _cffi_call_python(&_cffi_externpy__difftest_memcpy, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_non_reg_interrupt_pending =
  { "pypy-c-pydrofoil-riscv.difftest_non_reg_interrupt_pending", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_non_reg_interrupt_pending(diff_non_reg_int * a0)
{
  char a[8];
  char *p = a;
  *(diff_non_reg_int * *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_non_reg_interrupt_pending, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_pmp_cfg_cpy =
  { "pypy-c-pydrofoil-riscv.difftest_pmp_cfg_cpy", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_pmp_cfg_cpy(void * a0, _Bool a1)
{
  char a[16];
  char *p = a;
  *(void * *)(p + 0) = a0;
  *(_Bool *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__difftest_pmp_cfg_cpy, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_pmpcpy =
  { "pypy-c-pydrofoil-riscv.difftest_pmpcpy", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_pmpcpy(void * a0, _Bool a1)
{
  char a[16];
  char *p = a;
  *(void * *)(p + 0) = a0;
  *(_Bool *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__difftest_pmpcpy, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_raise_critical_error =
  { "pypy-c-pydrofoil-riscv.difftest_raise_critical_error", (int)sizeof(_Bool), 0, 0 };

CFFI_DLLEXPORT _Bool difftest_raise_critical_error(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy__difftest_raise_critical_error, p);
  return *(_Bool *)p;
}

static struct _cffi_externpy_s _cffi_externpy__difftest_raise_intr =
  { "pypy-c-pydrofoil-riscv.difftest_raise_intr", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_raise_intr(uint64_t a0)
{
  char a[8];
  char *p = a;
  *(uint64_t *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_raise_intr, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_regcpy =
  { "pypy-c-pydrofoil-riscv.difftest_regcpy", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_regcpy(diff_context_t * a0, _Bool a1, _Bool a2)
{
  char a[24];
  char *p = a;
  *(diff_context_t * *)(p + 0) = a0;
  *(_Bool *)(p + 8) = a1;
  *(_Bool *)(p + 16) = a2;
  _cffi_call_python(&_cffi_externpy__difftest_regcpy, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_set_mhartid =
  { "pypy-c-pydrofoil-riscv.difftest_set_mhartid", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_set_mhartid(int a0)
{
  char a[8];
  char *p = a;
  *(int *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_set_mhartid, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_set_ramsize =
  { "pypy-c-pydrofoil-riscv.difftest_set_ramsize", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_set_ramsize(size_t a0)
{
  char a[8];
  char *p = a;
  *(size_t *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_set_ramsize, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_skip_one =
  { "pypy-c-pydrofoil-riscv.difftest_skip_one", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_skip_one(_Bool a0, _Bool a1, uint32_t a2, uint64_t a3)
{
  char a[32];
  char *p = a;
  *(_Bool *)(p + 0) = a0;
  *(_Bool *)(p + 8) = a1;
  *(uint32_t *)(p + 16) = a2;
  *(uint64_t *)(p + 24) = a3;
  _cffi_call_python(&_cffi_externpy__difftest_skip_one, p);
}

static struct _cffi_externpy_s _cffi_externpy__difftest_store_commit =
  { "pypy-c-pydrofoil-riscv.difftest_store_commit", (int)sizeof(int), 0, 0 };

CFFI_DLLEXPORT int difftest_store_commit(uint64_t * a0, uint64_t * a1, uint8_t * a2)
{
  char a[24];
  char *p = a;
  *(uint64_t * *)(p + 0) = a0;
  *(uint64_t * *)(p + 8) = a1;
  *(uint8_t * *)(p + 16) = a2;
  _cffi_call_python(&_cffi_externpy__difftest_store_commit, p);
  return *(int *)p;
}

static struct _cffi_externpy_s _cffi_externpy__difftest_uarchstatus_sync =
  { "pypy-c-pydrofoil-riscv.difftest_uarchstatus_sync", 0, 0, 0 };

CFFI_DLLEXPORT void difftest_uarchstatus_sync(diff_uarch_status * a0)
{
  char a[8];
  char *p = a;
  *(diff_uarch_status * *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__difftest_uarchstatus_sync, p);
}

static struct _cffi_externpy_s _cffi_externpy__isa_reg_display =
  { "pypy-c-pydrofoil-riscv.isa_reg_display", 0, 0, 0 };

CFFI_DLLEXPORT void isa_reg_display(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy__isa_reg_display, p);
}

static struct _cffi_externpy_s _cffi_externpy__update_dynamic_config =
  { "pypy-c-pydrofoil-riscv.update_dynamic_config", 0, 0, 0 };

CFFI_DLLEXPORT void update_dynamic_config(diff_ref_config * a0)
{
  char a[8];
  char *p = a;
  *(diff_ref_config * *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__update_dynamic_config, p);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "debug_mem_sync", (void *)&_cffi_externpy__debug_mem_sync, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 99), (void *)debug_mem_sync },
  { "difftest_close", (void *)&_cffi_externpy__difftest_close, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 103), (void *)difftest_close },
  { "difftest_csrcpy", (void *)&_cffi_externpy__difftest_csrcpy, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 102), (void *)difftest_csrcpy },
  { "difftest_dirty_fsvs", (void *)&_cffi_externpy__difftest_dirty_fsvs, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 98), (void *)difftest_dirty_fsvs },
  { "difftest_disambiguation_state", (void *)&_cffi_externpy__difftest_disambiguation_state, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 73), (void *)difftest_disambiguation_state },
  { "difftest_display", (void *)&_cffi_externpy__difftest_display, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 103), (void *)difftest_display },
  { "difftest_exec", (void *)&_cffi_externpy__difftest_exec, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 98), (void *)difftest_exec },
  { "difftest_guided_exec", (void *)&_cffi_externpy__difftest_guided_exec, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 79), (void *)difftest_guided_exec },
  { "difftest_init", (void *)&_cffi_externpy__difftest_init, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 96), (void *)difftest_init },
  { "difftest_load_flash", (void *)&_cffi_externpy__difftest_load_flash, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 91), (void *)difftest_load_flash },
  { "difftest_load_flash_v2", (void *)&_cffi_externpy__difftest_load_flash_v2, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 101), (void *)difftest_load_flash_v2 },
  { "difftest_memcpy", (void *)&_cffi_externpy__difftest_memcpy, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 100), (void *)difftest_memcpy },
  { "difftest_non_reg_interrupt_pending", (void *)&_cffi_externpy__difftest_non_reg_interrupt_pending, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 93), (void *)difftest_non_reg_interrupt_pending },
  { "difftest_pmp_cfg_cpy", (void *)&_cffi_externpy__difftest_pmp_cfg_cpy, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 102), (void *)difftest_pmp_cfg_cpy },
  { "difftest_pmpcpy", (void *)&_cffi_externpy__difftest_pmpcpy, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 102), (void *)difftest_pmpcpy },
  { "difftest_raise_critical_error", (void *)&_cffi_externpy__difftest_raise_critical_error, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 66), (void *)difftest_raise_critical_error },
  { "difftest_raise_intr", (void *)&_cffi_externpy__difftest_raise_intr, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 98), (void *)difftest_raise_intr },
  { "difftest_regcpy", (void *)&_cffi_externpy__difftest_regcpy, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 92), (void *)difftest_regcpy },
  { "difftest_set_mhartid", (void *)&_cffi_externpy__difftest_set_mhartid, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 96), (void *)difftest_set_mhartid },
  { "difftest_set_ramsize", (void *)&_cffi_externpy__difftest_set_ramsize, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 97), (void *)difftest_set_ramsize },
  { "difftest_skip_one", (void *)&_cffi_externpy__difftest_skip_one, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 90), (void *)difftest_skip_one },
  { "difftest_store_commit", (void *)&_cffi_externpy__difftest_store_commit, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 72), (void *)difftest_store_commit },
  { "difftest_uarchstatus_sync", (void *)&_cffi_externpy__difftest_uarchstatus_sync, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 95), (void *)difftest_uarchstatus_sync },
  { "isa_reg_display", (void *)&_cffi_externpy__isa_reg_display, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 103), (void *)isa_reg_display },
  { "update_dynamic_config", (void *)&_cffi_externpy__update_dynamic_config, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 94), (void *)update_dynamic_config },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "gpr", offsetof(diff_context_t, gpr),
           sizeof(((diff_context_t *)0)->gpr),
           _CFFI_OP(_CFFI_OP_NOOP, 82) },
  { "fpr", offsetof(diff_context_t, fpr),
           sizeof(((diff_context_t *)0)->fpr),
           _CFFI_OP(_CFFI_OP_NOOP, 82) },
  { "priv", offsetof(diff_context_t, priv),
            sizeof(((diff_context_t *)0)->priv),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mstatus", offsetof(diff_context_t, mstatus),
               sizeof(((diff_context_t *)0)->mstatus),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "sstatus", offsetof(diff_context_t, sstatus),
               sizeof(((diff_context_t *)0)->sstatus),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mepc", offsetof(diff_context_t, mepc),
            sizeof(((diff_context_t *)0)->mepc),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "sepc", offsetof(diff_context_t, sepc),
            sizeof(((diff_context_t *)0)->sepc),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mtval", offsetof(diff_context_t, mtval),
             sizeof(((diff_context_t *)0)->mtval),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "stval", offsetof(diff_context_t, stval),
             sizeof(((diff_context_t *)0)->stval),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mtvec", offsetof(diff_context_t, mtvec),
             sizeof(((diff_context_t *)0)->mtvec),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "stvec", offsetof(diff_context_t, stvec),
             sizeof(((diff_context_t *)0)->stvec),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mcause", offsetof(diff_context_t, mcause),
              sizeof(((diff_context_t *)0)->mcause),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "scause", offsetof(diff_context_t, scause),
              sizeof(((diff_context_t *)0)->scause),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "satp", offsetof(diff_context_t, satp),
            sizeof(((diff_context_t *)0)->satp),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mip", offsetof(diff_context_t, mip),
           sizeof(((diff_context_t *)0)->mip),
           _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mie", offsetof(diff_context_t, mie),
           sizeof(((diff_context_t *)0)->mie),
           _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mscratch", offsetof(diff_context_t, mscratch),
                sizeof(((diff_context_t *)0)->mscratch),
                _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "sscratch", offsetof(diff_context_t, sscratch),
                sizeof(((diff_context_t *)0)->sscratch),
                _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mideleg", offsetof(diff_context_t, mideleg),
               sizeof(((diff_context_t *)0)->mideleg),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "medeleg", offsetof(diff_context_t, medeleg),
               sizeof(((diff_context_t *)0)->medeleg),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "pc", offsetof(diff_context_t, pc),
          sizeof(((diff_context_t *)0)->pc),
          _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "v", offsetof(diff_context_t, v),
         sizeof(((diff_context_t *)0)->v),
         _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mtval2", offsetof(diff_context_t, mtval2),
              sizeof(((diff_context_t *)0)->mtval2),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "mtinst", offsetof(diff_context_t, mtinst),
              sizeof(((diff_context_t *)0)->mtinst),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "hstatus", offsetof(diff_context_t, hstatus),
               sizeof(((diff_context_t *)0)->hstatus),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "hideleg", offsetof(diff_context_t, hideleg),
               sizeof(((diff_context_t *)0)->hideleg),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "hedeleg", offsetof(diff_context_t, hedeleg),
               sizeof(((diff_context_t *)0)->hedeleg),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "hcounteren", offsetof(diff_context_t, hcounteren),
                  sizeof(((diff_context_t *)0)->hcounteren),
                  _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "htval", offsetof(diff_context_t, htval),
             sizeof(((diff_context_t *)0)->htval),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "htinst", offsetof(diff_context_t, htinst),
              sizeof(((diff_context_t *)0)->htinst),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "hgatp", offsetof(diff_context_t, hgatp),
             sizeof(((diff_context_t *)0)->hgatp),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vsstatus", offsetof(diff_context_t, vsstatus),
                sizeof(((diff_context_t *)0)->vsstatus),
                _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vstvec", offsetof(diff_context_t, vstvec),
              sizeof(((diff_context_t *)0)->vstvec),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vsepc", offsetof(diff_context_t, vsepc),
             sizeof(((diff_context_t *)0)->vsepc),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vscause", offsetof(diff_context_t, vscause),
               sizeof(((diff_context_t *)0)->vscause),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vstval", offsetof(diff_context_t, vstval),
              sizeof(((diff_context_t *)0)->vstval),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vsatp", offsetof(diff_context_t, vsatp),
             sizeof(((diff_context_t *)0)->vsatp),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vsscratch", offsetof(diff_context_t, vsscratch),
                 sizeof(((diff_context_t *)0)->vsscratch),
                 _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vr", offsetof(diff_context_t, vr),
          sizeof(((diff_context_t *)0)->vr),
          _CFFI_OP(_CFFI_OP_NOOP, 88) },
  { "vstart", offsetof(diff_context_t, vstart),
              sizeof(((diff_context_t *)0)->vstart),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vxsat", offsetof(diff_context_t, vxsat),
             sizeof(((diff_context_t *)0)->vxsat),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vxrm", offsetof(diff_context_t, vxrm),
            sizeof(((diff_context_t *)0)->vxrm),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vcsr", offsetof(diff_context_t, vcsr),
            sizeof(((diff_context_t *)0)->vcsr),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vl", offsetof(diff_context_t, vl),
          sizeof(((diff_context_t *)0)->vl),
          _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vtype", offsetof(diff_context_t, vtype),
             sizeof(((diff_context_t *)0)->vtype),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "vlenb", offsetof(diff_context_t, vlenb),
             sizeof(((diff_context_t *)0)->vlenb),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "fcsr", offsetof(diff_context_t, fcsr),
            sizeof(((diff_context_t *)0)->fcsr),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "tselect", offsetof(diff_context_t, tselect),
               sizeof(((diff_context_t *)0)->tselect),
               _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "tdata1", offsetof(diff_context_t, tdata1),
              sizeof(((diff_context_t *)0)->tdata1),
              _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "tinfo", offsetof(diff_context_t, tinfo),
             sizeof(((diff_context_t *)0)->tinfo),
             _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "debugMode", offsetof(diff_context_t, debugMode),
                 sizeof(((diff_context_t *)0)->debugMode),
                 _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "dcsr", offsetof(diff_context_t, dcsr),
            sizeof(((diff_context_t *)0)->dcsr),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "dpc", offsetof(diff_context_t, dpc),
           sizeof(((diff_context_t *)0)->dpc),
           _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "dscratch0", offsetof(diff_context_t, dscratch0),
                 sizeof(((diff_context_t *)0)->dscratch0),
                 _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "dscratch1", offsetof(diff_context_t, dscratch1),
                 sizeof(((diff_context_t *)0)->dscratch1),
                 _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "platform_irp_meip", offsetof(diff_non_reg_int, platform_irp_meip),
                         sizeof(((diff_non_reg_int *)0)->platform_irp_meip),
                         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "platform_irp_mtip", offsetof(diff_non_reg_int, platform_irp_mtip),
                         sizeof(((diff_non_reg_int *)0)->platform_irp_mtip),
                         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "platform_irp_msip", offsetof(diff_non_reg_int, platform_irp_msip),
                         sizeof(((diff_non_reg_int *)0)->platform_irp_msip),
                         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "platform_irp_seip", offsetof(diff_non_reg_int, platform_irp_seip),
                         sizeof(((diff_non_reg_int *)0)->platform_irp_seip),
                         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "platform_irp_stip", offsetof(diff_non_reg_int, platform_irp_stip),
                         sizeof(((diff_non_reg_int *)0)->platform_irp_stip),
                         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "platform_irp_vseip", offsetof(diff_non_reg_int, platform_irp_vseip),
                          sizeof(((diff_non_reg_int *)0)->platform_irp_vseip),
                          _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "platform_irp_vstip", offsetof(diff_non_reg_int, platform_irp_vstip),
                          sizeof(((diff_non_reg_int *)0)->platform_irp_vstip),
                          _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "lcofi_req", offsetof(diff_non_reg_int, lcofi_req),
                 sizeof(((diff_non_reg_int *)0)->lcofi_req),
                 _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "ignore_illegal_mem_access", offsetof(diff_ref_config, ignore_illegal_mem_access),
                                 sizeof(((diff_ref_config *)0)->ignore_illegal_mem_access),
                                 _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "debug_difftest", offsetof(diff_ref_config, debug_difftest),
                      sizeof(((diff_ref_config *)0)->debug_difftest),
                      _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "sc_failed", offsetof(diff_uarch_status, sc_failed),
                 sizeof(((diff_uarch_status *)0)->sc_failed),
                 _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "_64", (size_t)-1,
           (size_t)-1,
           _CFFI_OP(_CFFI_OP_NOOP, 80) },
  { "_32", (size_t)-1,
           (size_t)-1,
           _CFFI_OP(_CFFI_OP_NOOP, 77) },
  { "_16", (size_t)-1,
           (size_t)-1,
           _CFFI_OP(_CFFI_OP_NOOP, 75) },
  { "_8", (size_t)-1,
          (size_t)-1,
          _CFFI_OP(_CFFI_OP_NOOP, 85) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$1", 87, _CFFI_F_UNION|_CFFI_F_CHECK_FIELDS,
    (size_t)-2, -2, 66, 4 /* unnamed */ },
  { "$diff_context_t", 68, _CFFI_F_CHECK_FIELDS,
    sizeof(diff_context_t), offsetof(struct _cffi_align_typedef_diff_context_t, y), 0, 55 },
  { "$diff_non_reg_int", 69, _CFFI_F_CHECK_FIELDS,
    sizeof(diff_non_reg_int), offsetof(struct _cffi_align_typedef_diff_non_reg_int, y), 55, 8 },
  { "$diff_ref_config", 70, _CFFI_F_CHECK_FIELDS,
    sizeof(diff_ref_config), offsetof(struct _cffi_align_typedef_diff_ref_config, y), 63, 2 },
  { "$diff_uarch_status", 71, _CFFI_F_CHECK_FIELDS,
    sizeof(diff_uarch_status), offsetof(struct _cffi_align_typedef_diff_uarch_status, y), 65, 1 },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "diff_context_t", 68 },
  { "diff_non_reg_int", 69 },
  { "diff_ref_config", 70 },
  { "diff_uarch_status", 71 },
  { "reg_t", 16 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  25,  /* num_globals */
  5,  /* num_struct_unions */
  0,  /* num_enums */
  5,  /* num_typenames */
  NULL,  /* no includes */
  105,  /* num_types */
  1,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_pypy-c-pydrofoil-riscv(const void *p[])
{
    if (((intptr_t)p[0]) >= 0x0A03) {
        _cffi_call_python_org = (void(*)(struct _cffi_externpy_s *, char *))p[1];
    }
    p[0] = (const void *)0x2701;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_pypy-c-pydrofoil-riscv(void) { return NULL; }
#  else
     initpypy-c-pydrofoil-riscv(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_pypy-c-pydrofoil-riscv(void)
{
  return _cffi_init("pypy-c-pydrofoil-riscv", 0x2701, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initpypy-c-pydrofoil-riscv(void)
{
  _cffi_init("pypy-c-pydrofoil-riscv", 0x2701, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
