name: Arm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

# Limit tests to latest commit on branches other than main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4

    - name: Set up PyPy 2.7
      uses: actions/setup-python@v5
      with:
        python-version: "pypy-2.7-v7.3.10"

    - name: Restore cached IR
      id: cache-ir-restore
      uses: actions/cache/restore@v4
      with:
        path: arm/armv9.ir
        key: ${{ matrix.os }}

    - name: Build IR file
      if: steps.cache-ir-restore.outputs.cache-hit != 'true'
      run: |
        sudo add-apt-repository -y ppa:avsm/ppa
        sudo apt install -y opam zlib1g-dev pkg-config libgmp-dev z3
        opam init --disable-sandboxing -y
        make regen-arm-ir-files

    - name: Save cached IR
      if: steps.cache-ir-restore.outputs.cache-hit != 'true'
      id: cache-ir-save
      uses: actions/cache/save@v4
      with:
        path: arm/armv9.ir
        key: ${{ steps.cache-ir-restore.outputs.cache-primary-key }}

    - name: Run ARM unit test
      run: |
        make pydrofoil-test-arm

    - name: build ARM
      run: |
        make pypy_binary/bin/python pypy2/rpython/bin/rpython arm/armv9.ir
        PYTHONPATH=. pypy_binary/bin/python pypy2/rpython/bin/rpython -Ojit --translation-withsmallfuncsets=0 --translation-jit_opencoder_model=big --output=pydrofoil-arm arm/targetarm.py --no-arm-regen

    - name: boot linux
      run: |
        PYPYLOG=jit-summary:summary ./pydrofoil-arm -b 0x80000000,arm/bootloader.bin -b 0x81000000,arm/sail.dtb -b 0x82080000,arm/Image -C cpu.cpu0.RVBAR=0x80000000 -C cpu.has_tlb=0x0  -l 23_000_000 2> /dev/null

    - name: show jit summary booting
      run: |
        cat summary
