name: CHERIoT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

# Limit tests to latest commit on branches other than main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v3

    - name: Set up PyPy 2.7
      uses: actions/setup-python@v4
      with:
        python-version: "pypy-2.7-v7.3.10"

    - name: install dependencies and create virtualenv
      run: |
        make pypy_binary/bin/python
        make pypy2/rpython/bin/rpython

    - name: install opam
      run: |
        sudo add-apt-repository -y ppa:avsm/ppa
        sudo apt install -y opam zlib1g-dev pkg-config libgmp-dev z3

    - name: Init opam
      run: opam init --disable-sandboxing -y

    - name: Generate ir files
      run: |
        make regen-cheriot-ir-files

    - name: Test with pytest
      run: |
        make pydrofoil-cheriot-test

    - name: Translate and run binary
      run: |
        make pydrofoil-cheriot

    - name: Run CHERIoT tests
      run: |
        ./pydrofoil-riscv cheriot/input/hello_world -l 491627
        ./pydrofoil-riscv cheriot/input/test_suite

    - name: Run allocator_benchmark
      run: |
        ./pydrofoil-riscv cheriot/input/allocator_benchmark -l 274595167

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: pydrofoil-cheriot-${{ matrix.os }}
        path: ./pydrofoil-cheriot
