name: Pydrofoil-from-sail

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

# Limit tests to latest commit on branches other than main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Add opam2 PPA and install opam (ubuntu)
      run: |
        sudo add-apt-repository -y ppa:avsm/ppa
        sudo apt install -y opam zlib1g-dev pkg-config libgmp-dev z3
      if: contains(matrix.os, 'ubuntu')

    - name: Add opam2 PPA and install opam (macos)
      run: |
        brew install opam z3 zlib
      if: contains(matrix.os, 'macos')

    - name: Init opam
      run: opam init --disable-sandboxing -y

    - uses: actions/checkout@v4
      with:
        repository: riscv/sail-riscv
        ref: 87f8bb34d629163563515a82102c48b722ab9058

    - uses: actions/checkout@v4
      with:
        path: pydrofoil
      name: Pre-emptively checkout pydrofoil to get the correct branch

    - name: download and run build script
      run: |
        wget https://raw.githubusercontent.com/pydrofoil/pydrofoil/main/build-pydrofoil-from-sail.sh
        chmod a+x build-pydrofoil-from-sail.sh
        ./build-pydrofoil-from-sail.sh

    - name: run two tests
      run: |
        ./pydrofoil-riscv --rv32 test/riscv-tests/rv32ui-p-addi.elf
        ./pydrofoil-riscv test/riscv-tests/rv64ui-p-addi.elf

